# Generated by Django 5.1.5 on 2025-01-21 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0003_faculty_description_en_faculty_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='building_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='building_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='room_number_en',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='room_number_ru',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='department_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='univer.faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='department_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='univer.faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='professor_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='univer.professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='univer.professor'),
        ),
        migrations.AddField(
            model_name='courseenrolled',
            name='grade_en',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='courseenrolled',
            name='grade_ru',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='feedback_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='feedback_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='day_of_week_en',
            field=models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='day_of_week_ru',
            field=models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница')], max_length=20, null=True),
        ),
    ]
